name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: oven-sh/setup-bun@v2
      
      - name: Install dependencies
        run: bun install

      - name: Build
        run: npm run compile

      - run: bunx pkg-pr-new publish
